### ISSUE TITLE
Darken my blogging website!

### ISSUE THREAD

**Issue by EdgeKing810** [kinesisgamesblog/kinesisgamesblog.github.io#1]
I'm a fan of dark websites. Turn the website into a dark mode with proper accent colors and all. Make sure that elements just don't get barely visible.

First one submitting a proper and quality PR has my green flag. Some basic knowledge and searching around how jekyll works will most likely help btw. For changing looks, ``_config.yml`` will probably be your best bet. Makes use of markdown too so shouldn't be too hard.

>For beginners:
 >   * Fork this repo.
 >   * Clone **your** forked repo and make the required changes.
 >   * Can be previewed how the final page will look by opening ``index.html`` in a web browser.
 >   * Search about and submit a Pull Request!

**Comment by benknoble** [comment]
Has anyone stepped up to work on this?

What kind of theming/colors are you looking for? Do you want dark mode (i.e. a toggle) or just a dark theme (i.e., set once and forever, until you change it in the source)?

**Comment by EdgeKing810** [comment]
Nope. If you want to work on this, I'll assign you.

No toggle. Just a pretty background dark theme with pretty colors for text/buttons like a light shiny blue.

**Comment by karan171996** [comment]
I love to contribute!!!

**Comment by EdgeKing810** [comment]
Anyone who wants to work on this and will, just tell me. I'll assign you and your PR subsequently will most probably be the one that will be accepted.
